# Generated by Django 2.2 on 2021-05-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210501_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['publish_date', '-updated', '-timestamp']},
        ),
    ]
